### ISSUE TITLE
Question about edge models.

### ISSUE THREAD

**Issue by SqySimmon** [StanfordASL/Trajectron-plus-plus#12]
Thank you for your nice work !
I saw PointNet and attention combination methods between agents within each type of edges here:
https://github.com/StanfordASL/Trajectron-plus-plus/blob/b99e07dcabba06aab14135a79ac19e77d2baa314/trajectron/model/mgcvae.py#L231-L258
But it seems that they are never used. Have you do some experiments about that? What about the results?
https://github.com/StanfordASL/Trajectron-plus-plus/blob/b99e07dcabba06aab14135a79ac19e77d2baa314/trajectron/model/mgcvae.py#L532-L539

**Comment by BorisIvanovic** [comment]
Hi @SqySimmon , thanks for your question. 

You're correct that they're never used. We tried to use these with an earlier version of the model, and observed the following:
- Using either of TemporallyBatchedAdditiveAttention or PointNet sharply increased our model's runtime (remember, any method used to combine edges of the same type needs to be applied to all edges, which can be many more than the number of nodes). Runtime is important for us as we are focusing on robotic use cases, so this is already a problem.
- Performance-wise, we tried these and other (simpler/faster) methods of same-type edge combination and found that their performance wasn't better than the simple summation we use now, so we left it as-is. 

As for why they're still in the codebase: We didn't want to remove them in case there are some future improvements that would enable their applicability.
