### ISSUE TITLE
[QUESTION] How to use Trajectron++ with personal dataset?

### ISSUE THREAD

**Issue by lorience** [StanfordASL/Trajectron-plus-plus#16]
Hello,

I would like to know whether there is an explanation of preparing the personal dataset in order to work with trajectron++?

I want to test trajectron++ with apolloscape dataset too. How should the dataset be in order to train this model? 

Thank you.

**Comment by BorisIvanovic** [comment]
Hi @lorience, thanks for the question!

There's no current explanation, so I guess this will serve as one :P 

Broadly, the data structure that we've adopted for this model is as follows:

1. At the highest level, there is an [Environment](https://github.com/StanfordASL/Trajectron-plus-plus/blob/master/trajectron/environment/environment.py) object that holds general dataset information, as well as...
2. A list of [Scene](https://github.com/StanfordASL/Trajectron-plus-plus/blob/master/trajectron/environment/scene.py) objects. These hold information about the agents and their interactions for a specific scenario (this will be something like a 10 second scene or something like that from a dataset). Finally, each Scene holds many
3. [Node](https://github.com/StanfordASL/Trajectron-plus-plus/blob/master/trajectron/environment/node.py) objects. These represent each agent in the scene, as well as their data (positions, velocities, acceleration, etc.).

As for how to go from raw data to such a format, I think what we did for the nuScenes and pedestrian datasets should provide a good reference:

- [nuScenes preprocessing script](https://github.com/StanfordASL/Trajectron-plus-plus/blob/master/experiments/nuScenes/process_data.py)
- [pedestrians preprocessing script](https://github.com/StanfordASL/Trajectron-plus-plus/blob/master/experiments/pedestrians/process_data.py)

Hope this helps!

**Comment by BorisIvanovic** [comment]
Closing for now, good luck!
