### ISSUE TITLE
Computation of Average Error (FDE/ADE) ETH/UCY

### ISSUE THREAD

**Issue by os1a** [StanfordASL/Trajectron-plus-plus#19]
Hi,
I have noticed that the reported average errors in table 1 in your paper are not consistent with the baselines. You are computing the average of all testing samples without taking into account the scenes they belong to. However, as done in most related works (S-GAN), the average is taken over scenes. This makes more sense as you do not want a large scene (e.g, univ with 24k samples) to dominate the average.

For example, S-GAN FDEs are (1.52,1.61,1.26,0.69,0.84), by averaging them you get 1.18 (as reported in the paper). However, if you compute the average over all testing samples from all scenes (as you do for your method), you will get 1.16.

Best,
Osama

**Comment by BorisIvanovic** [comment]
Hi @os1a,

Good eye!! Thank you for bringing this up, I wish I heard this before the ECCV camera-ready deadline, but alas :P 

I will leave this issue open until I update the arXiv version of the paper and I will let you know when it is done (I was aiming to do this next week anyways).

Thank you!
Boris

**Comment by os1a** [comment]
Thanks for covering this, I was experimenting with your nice approach and would like to combine with other ideas I had before about the multimodality of the prediction. Mainly comparing the CVAE to the EWTA (as in https://arxiv.org/abs/1906.03631) to get a sense of which method given the same inputs modalities and architecture could lead to better diversity.

Best,
Osama
