### ISSUE TITLE
key error "arcline_path_3" when processing nuScenes data

### ISSUE THREAD

**Issue by MoonBlvd** [StanfordASL/Trajectron-plus-plus#20]
Hi,

I'm following the instruction to prepare nuScenes data. 

This is the command I'm using `python process_data.py --data=/mnt/workspace/datasets/nuscenes/ --version="v1.0-trainval" --output_path=../processed` 

I found that the original cammand doesn't work for my case as it is looking for a folder named "v1.0"

When I ran this command, I got this error: 

```
Traceback (most recent call last):
  File "process_data.py", line 472, in <module>
    process_data(args.data, args.version, args.output_path, args.val_split)
  File "process_data.py", line 432, in process_data
    scene = process_scene(ns_scene, env, nusc, data_path)
  File "process_data.py", line 256, in process_scene
    nusc_map = NuScenesMap(dataroot=data_path, map_name=map_name)
  File "/home/brianyao/anaconda3/lib/python3.7/site-packages/nuscenes/map_expansion/map_api.py", line 92, in __init__
    self._load_layers()
  File "/home/brianyao/anaconda3/lib/python3.7/site-packages/nuscenes/map_expansion/map_api.py", line 143, in _load_layers
    self.arcline_path_3 = self._load_arcline_path()
  File "/home/brianyao/anaconda3/lib/python3.7/site-packages/nuscenes/map_expansion/map_api.py", line 120, in _load_arcline_path
    return self.json_obj['arcline_path_3']
KeyError: 'arcline_path_3'
```

It seems that the map dictionary does not have the key the API is looking for. Could you please let me know how to fix it?

**Comment by mzahran001** [comment]
Hi @MoonBlvd 

Two questions:
- What is the map version that you are using? Is it Map expansion pack (v1.2)?
- Can you also double-check that you are using the latest nuScenes devkit?
```
pip install nuscenes-devkit -U
```

**Comment by MoonBlvd** [comment]
Hi @mzahran001 I tried v1.1 accoding to your repo and it gave me that error. As to the devkit, I used the same command to install nuscenes-devkit today so I'm assuming it's the latest?

**Comment by mzahran001** [comment]
I guess this is the issue, try to update the maps to **Map expansion pack (v1.2)**.

**Comment by MoonBlvd** [comment]
@mzahran001 Great, it works now! Thank you! Will close the issue.

**Comment by triple-tam** [comment]
Map expansion pack v1.2 fixes the issue for me as well.
Additionally, these are the other commands I ran:
```
cd experiments/nuScenes
mkdir processed
python process_data.py --data=./v1.0-mini --version="v1.0-mini" --output_path=./processed
```
Note that it is `./processed` and not `../processed`
