### ISSUE TITLE
Great performance difference on validation dataset and testing dataset

### ISSUE THREAD

**Issue by simmonssong** [StanfordASL/Trajectron-plus-plus#28]
I made some modeling practice by myself. But the result is little bit weird. The ADE/FDE was low in validation dataset but it was extremely high in testing dataset. Have you met with this problem? I wonder whether the distributions of datasets these are similar. Thank you !

**Comment by BorisIvanovic** [comment]
Hi @simmonssong,

Could you give me a bit more information about what you're trying to do? I don't know which dataset you're referring to here

**Comment by simmonssong** [comment]
@BorisIvanovic Hi, Did you check the distributions of train-set, validation-set, and test-set? Are the proportions between different kinds of trajectories the same? For instance, turning left, turning right, or going straight forward.

**Comment by BorisIvanovic** [comment]
Oh definitely not, there are _significantly_ more instances of trajectories going straight forward vs turning trajectories. 

We accounted for this in training by keeping counts of each trajectory type (using trajectory curvature as a proxy) and then re-weighting how often we sample them in each training batch to achieve balanced batches.

**Comment by simmonssong** [comment]
@BorisIvanovic Sorry, can you remind me about that in the code? I didn't find it in ```dataset.py``` or ```preprocessing.py```.

**Comment by simmonssong** [comment]
@BorisIvanovic I got it! You made rotation for all trajectories. So your work ignored the internal difference between different trajectories? (For example, turning or not.) But if many trajectories are just going straightforward without turning, whether the model would over-fit on this kind of pattern?

> Oh definitely not, there are _significantly_ more instances of trajectories going straight forward vs turning trajectories.
> 
> We accounted for this in training by keeping counts of each trajectory type (using trajectory curvature as a proxy) and then re-weighting how often we sample them in each training batch to achieve balanced batches.

**Comment by BorisIvanovic** [comment]
@simmonssong No worries! Here you can see where we count each type of trajectory (later we sample them according to this frequency): https://github.com/StanfordASL/Trajectron-plus-plus/blob/master/experiments/nuScenes/process_data.py#L339

This way, we balance the batches of data fed into the model so that it doesn't overfit to straight trajectories

**Comment by simmonssong** [comment]
Got it! Thx!
