### ISSUE TITLE
PicklingError while running the readme example

### ISSUE THREAD

**Issue by OlgerSiebinga** [StanfordASL/Trajectron-plus-plus#29]
When trying to run the pedestrian training from the example in the readme file, I ran into an issue. I cloned the repository, did the data setup part and then tried to run the following command (with line 38 in `train.py` commented out):

```
python train.py --eval_every 10 --vis_every 1 --train_data_dict eth_train.pkl --eval_data_dict eth_val.pkl --offline_scene_graph yes --preprocess_workers 5 --log_dir ../experiments/pedestrians/models --log_tag _eth_vel_ar3 --train_epochs 100 --augment --conf ../experiments/pedestrians/models/eth_vel/config.json --device cpu
``` 

This resulted in a `PicklingError` that seems to come from a multiprocessing implementation in a dataloader, but I cannot completely figure out what's going on. Could you please help me out with this issue? I'm using Python 3.6 on Windows 10 with all the dependency versions as specified in requirements.txt. The full output is:

```
python train.py --eval_every 10 --vis_every 1 --train_data_dict eth_train.pkl --eval_data_dict eth_val.pkl --offline_scene_graph yes --preprocess_workers 5 --log_dir ../experiments/pedestrians/models --log_tag _eth_vel_ar3 --train_epochs 100 --augment --conf ../experiments/pedestrians/models/eth_vel/config.json --device cpu
-----------------------
| TRAINING PARAMETERS |
-----------------------
| batch_size: 256
| device: cpu
| eval_device: cpu
| Offline Scene Graph Calculation: yes
| EE state_combine_method: sum
| EIE scheme: attention
| dynamic_edges: yes
| robot node: False
| edge_addition_filter: [0.25, 0.5, 0.75, 1.0]
| edge_removal_filter: [1.0, 0.0]
| MHL: 1
| PH: 12
-----------------------
Loaded training data from ../experiments/processed\eth_train.pkl
Loaded evaluation data from ../experiments/processed\eth_val.pkl
Offline calculating scene graphs
Created Scene Graph for Training Scene 0
Created Scene Graph for Training Scene 1
Created Scene Graph for Training Scene 2
Created Scene Graph for Training Scene 3
Created Scene Graph for Training Scene 4
Created Scene Graph for Training Scene 5
Created Scene Graph for Training Scene 6
Created Scene Graph for Evaluation Scene 0
Created Scene Graph for Evaluation Scene 1
Created Scene Graph for Evaluation Scene 2
Created Scene Graph for Evaluation Scene 3
Created Scene Graph for Evaluation Scene 4
Created Scene Graph for Evaluation Scene 5
Created Scene Graph for Evaluation Scene 6
Created Training Model.
Created Evaluation Model.
  0%|                                                   | 0/148 [00:03<?, ?it/s]
Traceback (most recent call last):
  File "C:/Users/Olger/PycharmProjects/Trajectron-plus-plus/trajectron/train.py", line 440, in <module>
    main()
  File "C:/Users/Olger/PycharmProjects/Trajectron-plus-plus/trajectron/train.py", line 251, in main
    for batch in pbar:
  File "C:\Users\Olger\PycharmProjects\Trajectron-plus-plus\venv\lib\site-packages\tqdm\std.py", line 1127, in __iter__
    for obj in iterable:
  File "C:\Users\Olger\PycharmProjects\Trajectron-plus-plus\venv\lib\site-packages\torch\utils\data\dataloader.py", line 279, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\Olger\PycharmProjects\Trajectron-plus-plus\venv\lib\site-packages\torch\utils\data\dataloader.py", line 719, in __init__
    w.start()
  File "C:\python36\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\python36\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\python36\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\python36\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\python36\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function augment at 0x0000020D25C677B8>: attribute lookup augment on __main__ failed

Process finished with exit code 1
```

**Comment by BorisIvanovic** [comment]
Hi @OlgerSiebinga, I'm sorry to hear that you ran into this issue.

Unfortunately, I don't have access to a Windows machine in order to reproduce the problem you're experiencing, so it is hard for me to help... Do you have any updates since you posted this?

**Comment by OlgerSiebinga** [comment]
Hi @BorisIvanovic, 
Yes I did make some progress. One workaround is to set --preprocess_workers to 0, this disables the multiprocessing so the error disappears, but it is also very inefficient. When I did that another error showed up though, in the `MultimodalGenerativeCVAE` class the `encode_node_history` and `encode_edge` methods use a `last_index_per_sequence` tensor to index their return values. But these tensors where of the wrong type, so I had to cast them to `long` to get this workaround working.

I've also managed to track the `PicklingError` to the `Scene` class, the problem is with the `aug_func` attribute. This function handle points to a function that cannot be found by the `pickle` module and that causes the error. The function handle that is passed to the Scene objects is created in `process_data.py`, and because that file was ran first, the pickle module look for a function called `augment` in the `__main__` namespace. I fixed it by defining the `augment` function in a separate *.py file, and importing it in `process_data.py`. This did fix the `PicklingError`, but I could not fully test this fix because now I get a `MemoryError`. This is probably because I'm running it on a laptop with limited resources now. After the holidays I'll have access to a better machine again and then I'll test if my fix solved the issue.

**Comment by BorisIvanovic** [comment]
Sounds good, thank you very much @OlgerSiebinga for the detailed information!!

**Comment by OlgerSiebinga** [comment]
I verified that the two fixes proposed above will make the script run on Windows 10. I did have to set the `--offline_scene_graph` to "no", because otherwise I ran out of memory (with 32 GB available, made me wonder how much you use, or do you only run the code on clusters?)

I could create a pull request if you want to, so you can make sure I didn't break anything.

**Comment by BorisIvanovic** [comment]
Lovely! Glad to hear that. As for RAM, the desktop I use has 64 GB so that's probably why I haven't encountered the same memory issue.

I think it'd be great if you could create a pull request! I won't actually merge it in to the codebase, but it will serve as a great reference for other users with similar issues!

Thank you very much @OlgerSiebinga!

**Comment by MZ82020** [comment]
@OlgerSiebinga Bonjour, 

J'ai pas compris comment vous avez fait précisément pour que l'erreur a disparu! Pouvez vous m'expliquer comment vous avez procédé s'il vous plait? 

Merci

**Comment by OlgerSiebinga** [comment]
Hi @MZ82020,

Sorry, my French is quite limited, so I'll answer in English.

**Comment by Fina0215** [comment]
> Hi @BorisIvanovic, Yes I did make some progress. One workaround is to set --preprocess_workers to 0, this disables the multiprocessing so the error disappears, but it is also very inefficient. When I did that another error showed up though, in the `MultimodalGenerativeCVAE` class the `encode_node_history` and `encode_edge` methods use a `last_index_per_sequence` tensor to index their return values. But these tensors where of the wrong type, so I had to cast them to `long` to get this workaround working.
> 
> I've also managed to track the `PicklingError` to the `Scene` class, the problem is with the `aug_func` attribute. This function handle points to a function that cannot be found by the `pickle` module and that causes the error. The function handle that is passed to the Scene objects is created in `process_data.py`, and because that file was ran first, the pickle module look for a function called `augment` in the `__main__` namespace. I fixed it by defining the `augment` function in a separate *.py file, and importing it in `process_data.py`. This did fix the `PicklingError`, but I could not fully test this fix because now I get a `MemoryError`. This is probably because I'm running it on a laptop with limited resources now. After the holidays I'll have access to a better machine again and then I'll test if my fix solved the issue.

Hi, I ran into the same issue too(PicklingError)."by defining the `augment` function in a separate *.py file, and importing it in `process_data.py`", could you please detail how to solve? Otherwise, may you send a copy of your code to my mailbox (bao1098902310@gmail.com). Thanks a lot for your help!

**Comment by samauro** [comment]
Hello, how is life in Cali?

I see I still receive updates. Am I still subscribed somehow?

Thank you!

Grt van Eindhoven,
Mauro

**Comment by MandyZhang4869** [comment]
> Hi @BorisIvanovic, Yes I did make some progress. One workaround is to set --preprocess_workers to 0, this disables the multiprocessing so the error disappears, but it is also very inefficient. When I did that another error showed up though, in the `MultimodalGenerativeCVAE` class the `encode_node_history` and `encode_edge` methods use a `last_index_per_sequence` tensor to index their return values. But these tensors where of the wrong type, so I had to cast them to `long` to get this workaround working.
> 
> I've also managed to track the `PicklingError` to the `Scene` class, the problem is with the `aug_func` attribute. This function handle points to a function that cannot be found by the `pickle` module and that causes the error. The function handle that is passed to the Scene objects is created in `process_data.py`, and because that file was ran first, the pickle module look for a function called `augment` in the `__main__` namespace. I fixed it by defining the `augment` function in a separate *.py file, and importing it in `process_data.py`. This did fix the `PicklingError`, but I could not fully test this fix because now I get a `MemoryError`. This is probably because I'm running it on a laptop with limited resources now. After the holidays I'll have access to a better machine again and then I'll test if my fix solved the issue.

I met the same situation, how did you finally solve it?  Can it only be solved by a better device？
