### ISSUE TITLE
Pre-processing documentation

### ISSUE THREAD

**Issue by mo-zahran** [StanfordASL/Trajectron-plus-plus#3]
Thanks for sharing this great work!
I have a quick question regarding data preprocessing, can you refer me to any available written resources about how you made the preprocessing and design choices?

**Comment by BorisIvanovic** [comment]
Hi @mo-zahran , thanks for the question.

Unfortunately, we don't really have any document that systematically lays out our preprocessing strategy or steps. I can tell you that most of the decisions we made were by trial and error, e.g., seeing which state components are actually useful or not. Neural network architecture design choices should largely be discussed in the Trajectron++ paper PDF.

Having said this, there will be a large-scale update to this codebase in the near future (following the upcoming public release of an updated version of the paper), so the exact preprocessing that was done will change soon.

**Comment by BorisIvanovic** [comment]
I'll close this now, but if you have additional questions please feel free to re-open it!
