### ISSUE TITLE
Typo in references of the Trajectron++ paper

### ISSUE THREAD

**Issue by MasterIzumi** [StanfordASL/Trajectron-plus-plus#31]
Hi, thanks for sharing your great work!
Here's a minor issue when I read the Trajectron++ paper: the authors' name of [11] and [18] are not correct, which confuse me a little bit. I think the corresponding papers should be [Deo et al.](https://arxiv.org/abs/1805.05499) and [MFP](https://arxiv.org/abs/1911.00997). :)

**Comment by BorisIvanovic** [comment]
Oh my goodness, I'm so sorry about that! Those are absolutely typos, thank you for bringing them to my attention!!

I will close this issue after I have updated the paper on arXiv.
