### ISSUE TITLE
Error of running evaluate.py

### ISSUE THREAD

**Issue by lylyjy** [StanfordASL/Trajectron-plus-plus#34]
Can you help me ?
Thanks.

(trajectron++) @LAPTOP-F22J3EPI:/mnt/e/google下载/Trajectron-plus-plus-master/experiments/nuScenes$ python evaluate.py --model models/vel_ee --checkpoint=12 --data ../processed/nuScenes_test_mini_full.pkl --output_path results --output_tag vel_ee --node_type VEHICLE --prediction_horizon 6

Loading from models/vel_ee/model_registrar-12.pt
Loaded!

-- Preparing Node Graph
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 26.66it/s]
Prediction Horizon: 6
-- Evaluating GMM Z Mode (Most Likely)
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.81it/s]
1.1392976582603214
-- Evaluating Full
  0%|                                                                                                                      | 0/2 [00:00<?, ?it/s]Segmentation fault (core dumped)

**Comment by BorisIvanovic** [comment]
Hi @lylyjy ,

Sorry for my late response! My first instinct is that your machine ran out of memory, although it's hard to tell without knowing the specifics of what you were trying to run and on what machine.

**Comment by BorisIvanovic** [comment]
I'm going to close this out for now because I feel like every time I've seen this on my machine it ended up being a memory issue (Same with the classic `Killed` message popping up out of nowhere). Please feel free to reopen it if you have further questions or information to share about the problem!
