### ISSUE TITLE
cannot find "csv/old/" for running "Result Analysis" notebook

### ISSUE THREAD

**Issue by MohammadHossein-Bahari** [StanfordASL/Trajectron-plus-plus#35]
Hello,

congrats for the great work and thanks for sharing the clean code with the community @BorisIvanovic.
While running "Result Analysis" notebook, it seems that 'csv/old/curr_*_errors.csv' files are missing.
Did I miss something or they are not provided?
Did anyone resolve the issue?

Thanks

**Comment by BorisIvanovic** [comment]
Hello @MohammadHossein-Bahari,

You can ignore those actually! Those CSVs contain the Trajectron and S-GAN results for comparison (and have nothing to do with evaluating Trajectron++). They're not included in the repository anyways and would have to be locally generated.
