### ISSUE TITLE
Looking for multi-modality in predictions

### ISSUE THREAD

**Issue by fireofearth** [StanfordASL/Trajectron-plus-plus#36]
Hi there!

First off, thank you for providing such a well maintained codebase. It is a pleasure to use, and I was able to set up and run code quite quickly!

My question is: I don't really see any multi-modality in the predictions. Am I doing this right?

For context, I'm sampling predictions from intersections in nuScenes like in the below overhead plot when cars can decide to go straight or turn left (diamond nodes: history, square nodes: ground truth).

![predict_scene39_t5_overhead](https://user-images.githubusercontent.com/14065660/110889167-80136680-82a2-11eb-9fa7-abf901f659e4.png)

To generate the predictions in the plot, I used the pretrained `int_ee_int` model
(from here https://github.com/StanfordASL/Trajectron-plus-plus/tree/master/experiments/nuScenes/models/int_ee_me ), calling it using the `predict()` function on test scene 39 (i.e. `nuScenes_test_full.pkl`), timestep 5 and prediction horizon 6, and 100 samples  like so (all options `z_mode`, ...etc set to `False`):

```
predictions = eval_stg.predict(scene,
            timesteps, ph, num_samples=num_samples,
            z_mode=False,
            gmm_mode=False,
            full_dist=False,
            all_z_sep=False)
```

It seems like the ego vehicle (center blue) can slow down and turn left, as the green car is doing. But not one of the 100 predictions go in that direction (so no evidence of multi-modality here). I'm running into similar situations when plotting other scenes and timesteps.

This runs counter to my expectations of what I read in the paper, where multimodality due to high level driver decisions is encoded using discrete latent variable z, and by sampling using the full output setting mentioned in page 8 of the Trajectron++ paper uses z ~ p(z | x), y ~ p(y | x,z). The sampling should reflect probability distribution over all possible high level decisions.

I've checked that `z_mode` `gmm_mode` `full_dist` `all_z_sep` all to `False` does this by essentially running the `predict()` function again on test scene 39, timestep 5 and prediction horizon 6, but this time plotting latent z values vs. value frequency instead:

![predict_scene39_t5_latents](https://user-images.githubusercontent.com/14065660/110889165-7f7ad000-82a2-11eb-8e90-76e34d484550.png)

So for most all vehicles, multiple values of z have non-zero frequency... Let me know if there is something wrong in my understanding.
  
For reference, this is how I'm sampling latent z:

```
def plot_latents_scene_timestep(
            scene, t,
            num_samples = 200,
            z_mode=False, gmm_mode = False, full_dist = False, all_z_sep = False):
    timesteps = np.array([t])
    # Trajectron.predict() arguments
    min_future_timesteps = 0
    min_history_timesteps = 1

    node_type = eval_stg.env.NodeType.VEHICLE
    if node_type not in eval_stg.pred_state:
        raise Exception("fail")

    model = eval_stg.node_models_dict[node_type]

    # Get Input data for node type and given timesteps
    batch = get_timesteps_data(env=eval_stg.env, scene=scene, t=timesteps, node_type=node_type, state=eval_stg.state,
                               pred_state=eval_stg.pred_state, edge_types=model.edge_types,
                               min_ht=min_history_timesteps, max_ht=eval_stg.max_ht, min_ft=min_future_timesteps,
                               max_ft=min_future_timesteps, hyperparams=eval_stg.hyperparams)
    # There are no nodes of type present for timestep
    if batch is None:
        raise Exception("fail")

    (first_history_index,
     x_t, y_t, x_st_t, y_st_t,
     neighbors_data_st,

     neighbors_edge_value,
     robot_traj_st_t,
     map), nodes, timesteps_o = batch

    x = x_t.to(eval_stg.device)
    x_st_t = x_st_t.to(eval_stg.device)
    if robot_traj_st_t is not None:
        robot_traj_st_t = robot_traj_st_t.to(eval_stg.device)
    if type(map) == torch.Tensor:
        map = map.to(eval_stg.device)

    # MultimodalGenerativeCVAE.predict() arguments
    inputs = x
    inputs_st = x_st_t
    first_history_indices = first_history_index
    neighbors = neighbors_data_st
    neighbors_edge_value = neighbors_edge_value
    robot = robot_traj_st_t
    prediction_horizon = ph

    mode = ModeKeys.PREDICT

    x, x_nr_t, _, y_r, _, n_s_t0 = model.obtain_encoded_tensors(mode=mode,
                                                               inputs=inputs,
                                                               inputs_st=inputs_st,
                                                               labels=None,
                                                               labels_st=None,
                                                               first_history_indices=first_history_indices,
                                                               neighbors=neighbors,
                                                               neighbors_edge_value=neighbors_edge_value,
                                                               robot=robot,
                                                               map=map)

    model.latent.p_dist = model.p_z_x(mode, x)
    z, num_samples, num_components = model.latent.sample_p(num_samples,
                                                          mode,
                                                          most_likely_z=z_mode,
                                                          full_dist=full_dist,
                                                          all_z_sep=all_z_sep)

    # after getting latents, Trajectron calls model.p_y_xz(). This part is not included here.
    
    # finally, plot the latents
    znp = z.detach().numpy()
    znp_counts = np.sum(znp, axis=0) / num_samples

    fig, ax = plt.subplots()
    ax.set_facecolor("grey")
    for idx, zz in enumerate(znp_counts):
        ax.plot(range(25), zz, c=AGENT_COLORS[idx % NCOLORS])
    n_vehicles = znp_counts.shape[0]
    ax.set_xlabel("z = value")
    ax.set_ylabel("p(z = value)")
    ax.set_title(f"Dist. latent values from {n_vehicles} vehicles ")
    savepath = 'plots/predict_scene{}_t{}{}_latents.png'.format(scene.name, t, ptype)
    plt.savefig(savepath, dpi=80)
    plt.close('all')
```

**Comment by BorisIvanovic** [comment]
Hi @fireofearth, thank you for the kind words! I think you're doing it right!

Regarding the top plot, I don't know if I'd say that you don't have multimodality in those predictions. In particular, the red and green vehicles appear to show it. My thoughts for why you're not seeing the same for the blue vehicle is that it could be that its speed is too high or it's accelerating and so it's very unlikely that it'd suddenly slow down and turn. The reason I say this is that the red and green vehicles are moving slower than the blue vehicle (from the spacing of their history diamonds) and I could imagine that the blue vehicle is accelerating (it's possible that the blue history diamonds are becoming more spaced out closer to the current timestep, but it's hard to tell visually).

Regarding the bottom plot, there's definitely multimodality visible (in a literal sense; there are multiple peaks in p(z | x)), so all looks good there. 

Something else that could be happening is that this multimodality is manifesting itself physically as different speeds/accelerations, so even if most of the samples are going straight ahead there could be variations within, e.g., where z=1 are trajectories that are slower than z=2, whose trajectories in turn are slower than z=3, etc.

**Comment by BorisIvanovic** [comment]
I'm going to close this out for now, please feel free to reopen it if you have further questions though!

**Comment by fireofearth** [comment]
Thanks. Yes, the confirmation is enough fore me to go on. You're explanation makes sense, and I also had a look at another one of your papers "Multimodal Deep Generative Models for Trajectory Prediction: A Conditional Variational Autoencoder Approach"
https://arxiv.org/abs/2008.03880 that reinforces what you said that multimodality arises from the factors you described.

**Comment by QiyangZ** [comment]
Hello @fireofearth , 
could you please tell me how you plotted multi-trajectories at the same time in the map? For example, the green one, there are many green lines and small green circles on each line, I wonder how these came out, could you please tell me that? You wrote another plotting script by yourself or just config the exiting code from this Trojectron++ repository?

Thank you in advance! :-)
