### ISSUE TITLE
The input_dict structure

### ISSUE THREAD

**Issue by isamoazen** [StanfordASL/Trajectron-plus-plus#39]
Hello,

Thank you for your great work. I am trying to implement your work in a simulation with CARLA and ROS. So, I need to construct input_dict from the agents of the CARLA. My question is, what is the structure of the input_dict?

When I print the input_dict in TEST_ONLINE, I get such output:

{PEDESTRIAN/8f9839e21b0f49c0b4c83ac13f181ba8: array([[ 1.20141e+02,  1.82161e+02, -4.60000e-02, -1.58300e+00,
        -1.00000e-03, -1.00000e-03]]), VEHICLE/ego: array([[ 1.11872679e+02,  1.31562659e+02,  6.25481637e-04,
         2.97950239e-03,  5.76674011e-03, -2.56999843e-03,
        -1.15393238e-01, -8.65299210e-04]]), PEDESTRIAN/24082a541e824068815c8b6824360b39: array([[ 1.34033e+02,  1.23999e+02, -1.19600e+00, -4.90000e-01,
         6.00000e-03,  2.30000e-02]]), PEDESTRIAN/608723982c4f45e199437866a0d39316: array([[109.625, 160.496,  -0.353,  -1.006,  -0.486,   0.203]]), PEDESTRIAN/7d64812f02a14f1badd236c35d9f6390: array([[ 98.002, 109.91 ,   0.578,   1.009,  -0.204,   0.127]]), VEHICLE/35a767667a984516bf1feb228c03de03: array([[ 1.07359039e+02,  1.33984973e+02, -3.52359405e-04,
         2.48052092e-04,  1.19383105e-03, -8.25341035e-04,
        -6.14216360e-01,  6.22177394e-08]]),

Which seems to have global x, y and 4 other objects for PEDESTRIAN and 6 other objects for VEHICLE. What are they?

Thank you again for your great work :)

**Comment by BorisIvanovic** [comment]
Hi @isamoazen , thank you for the kind words! 

The other 4 values for pedestrians are velocity in the x direction, velocity in the y direction, acceleration in the x direction, and acceleration in the y direction.

The other 8 values for vehicles are the x,y velocities, x,y accelerations, the norms of the velocity and acceleration, and the heading and change in heading (I think, it's been a while).

Also! If you are trying to make the model run with CARLA and ROS, I actually think I might be able to point you to a repo which has done the same! https://github.com/fishberg/cogrob-trajectron-mods and https://github.com/cog-rob-spring-2020/intent-inferencing-gc
