### ISSUE TITLE
Map pretrained model

### ISSUE THREAD

**Issue by shoaibazam** [StanfordASL/Trajectron-plus-plus#4]
Hi, 
I would like to know about the map pretrained model. As I am training the model but it gives me error
'weight_trans/model_registrar-1499.pt' no such file. Kindly provide that pretrained file.
Thank you

**Comment by BorisIvanovic** [comment]
Hi @shoaibazam,

You can find a map pretrained model here: https://github.com/StanfordASL/Trajectron-plus-plus/tree/nuScenes_dataset/data/nuScenes/models/me_demo

You can also take a look at our qualitative notebook [here](https://github.com/StanfordASL/Trajectron-plus-plus/blob/nuScenes_dataset/code/notebooks/NuScenes%20Qualitative.ipynb) to see how to load and use the model.

**Comment by shoaibazam** [comment]
Thanks for your reply.
