### ISSUE TITLE
Derivatives of velocities/acceleration

### ISSUE THREAD

**Issue by os1a** [StanfordASL/Trajectron-plus-plus#40]
Hi,

Thanks for your nice work,

I have a question regarding the information contained for each agent at each time step (the so-called state). According to the code (ex, ETH-UCY), you have the position, velocity and acceleration on x-y. The latter two are computed from the first one by getting the derivatives of the position.

https://github.com/StanfordASL/Trajectron-plus-plus/blob/ef0165a93ee5ba8cdc14f9b999b3e00070cd8588/experiments/pedestrians/process_data.py#L55

There you are using the np.gradient to compute the derivatives. However, in my understanding, the np.gradient uses the central differences to compute the derivatives of 1d array. This means that your velocity at time step t is computed from the positions at time steps t-1 and t+1. Same would apply for the acceleration. If this is the case, then the n_s_t0 in your code:

https://github.com/StanfordASL/Trajectron-plus-plus/blob/ef0165a93ee5ba8cdc14f9b999b3e00070cd8588/trajectron/model/mgcvae.py#L417

would have information about the future time steps (t+1 and t+2) which is problematic since you should not give the network any information about the future to be predicted.

Maybe I am missing something, so I would love to hear back from you.

Best,

**Comment by BorisIvanovic** [comment]
Hi @os1a ,

You can see my answer to this here: https://github.com/StanfordASL/Trajectron-plus-plus/issues/26

You're not missing anything, it was my mistake at first (I didn't realize that's what np.gradient did, I thought it took the derivative as in np.ediff1d). Feel very free to change that to [np.ediff1d](https://numpy.org/doc/stable/reference/generated/numpy.ediff1d.html) or similar (making sure to divide by dt).

**Comment by os1a** [comment]
Thanks for your answer and looking forward to the updated version of your amazing work.

Just to make sure that I can do it the right way, can I replace the following file:

https://github.com/StanfordASL/Trajectron-plus-plus/blob/ef0165a93ee5ba8cdc14f9b999b3e00070cd8588/trajectron/environment/data_utils.py#L27

with:

dx[~np.isnan(x)] = np.pad(np.ediff1d(x[~np.isnan(x)]) / dt, (1, 0), 'constant', constant_values=(0, 0))

Best,

**Comment by BorisIvanovic** [comment]
There's actually quite a few ways to do this. For example, one way is what you posted above, another is the following:
```
def derivative_of(x, dt=1, radian=False):
    if radian:
        x = make_continuous_copy(x)

    not_nan_mask = ~np.isnan(x)
    masked_x = x[not_nan_mask]

    if masked_x.shape[-1] < 2:
        return np.zeros_like(x)

    dx = np.full_like(x, np.nan)
    dx[not_nan_mask] = np.ediff1d(masked_x, to_begin=(masked_x[1] - masked_x[0])) / dt

    return dx
```

Another is to just call `np.gradient` online on the history data (i.e., estimate the derivatives online, which was my original intention). Speaking of estimation (and keeping in theme with the dynamics focus of the paper), one could even use a Kalman Filter to filter the agent's state up to the current time (from its previously observed states as well as each agent's known dynamics).

So... it's a little bit open as to the method to use.

**Comment by os1a** [comment]
Thanks for your quick respond.

**Comment by os1a** [comment]
After retraining the network with your fix, I got the following results for the univ dataset:
ADE/FDE: (best of many): 0.31/0.55, deterministic (most likely): 0.53/1.19
in comparison to the results in your paper:
ADE/FDE: (best of many): 0.22/0.43, deterministic (most likely): 0.41/1.07

Best,

**Comment by BorisIvanovic** [comment]
Nice! Thanks for the update!

I'll close this for now and ping you when I have new results, just a heads up that it may take a little bit (I have less time during the day as I'm interning now and in between codebases)
