### ISSUE TITLE
Questions about Prediction with Map Encoding

### ISSUE THREAD

**Issue by judyhuang209** [StanfordASL/Trajectron-plus-plus#42]
Hello @BorisIvanovic,
    First of all, thank you for providing this amazing project. I have little experience in implementing such a big model and hoping to get same clarification from you. As mentioned in the title, I have some questions about Map Encoding.
    
1.  I looked into process_data.py and please correct me if I'm wrong, it looks like you are using the same map for all the frames throughout the same scene. 
https://github.com/StanfordASL/Trajectron-plus-plus/blob/ef0165a93ee5ba8cdc14f9b999b3e00070cd8588/experiments/nuScenes/process_data.py#L252

2.  As for the map info, I noticed that patch_box is the moving area of the whole Scene. I'm just wondering is there a way to implement distinct map info (let's say if we set the patch_box to (current_x, current_y, 50, 50) )for each Frame in the Scene, and whether it would be affecting the prediction process.  Because personally I think it would be more reasonable to get the map info around the car itself rather than get the whole map which includes moving area of the whole Scene. Please kindly correct me if I get anything wrong.
https://github.com/StanfordASL/Trajectron-plus-plus/blob/ef0165a93ee5ba8cdc14f9b999b3e00070cd8588/experiments/nuScenes/process_data.py#L259-L269

Hope I'm not missing anything, thank you! Looking forward to hearing from you!

Best Regards,

**Comment by BorisIvanovic** [comment]
Hello @judyhuang209, thank you for your kind words and I hope I can help answer your questions!

1. That's correct!
2. The map code is unfortunately a little strewn throughout the codebase, but we do actually implement what you describe. We do get the map info around each agent and only encode that (rather than the whole entire map). Here's the lines in the code that do this:
    Map information is first obtained during dataloading: https://github.com/StanfordASL/Trajectron-plus-plus/blob/master/trajectron/model/dataset/preprocessing.py#L166
    Then, the relevant cropping happens during data collation: https://github.com/StanfordASL/Trajectron-plus-plus/blob/master/trajectron/model/dataset/preprocessing.py#L35
    It is this cropped and rotated map information that gets encoded in the map encoder.

**Comment by judyhuang209** [comment]
Hello @BorisIvanovic , thank you so much for your early and informative explaining!  I'm closing this issue now, I'll open another one if I have further more questions, thanks again!
