### ISSUE TITLE
Exploding scale

### ISSUE THREAD

**Issue by Mirorrn** [StanfordASL/Trajectron-plus-plus#45]
Hello @BorisIvanovic,

I tried to learn a simple normal distribution instead of the GMM. When I learn with the log scale, it explodes very quickly, but if I limit the scale, e.g. with 0.01*sigmoid(logit_scale), the training converges. I wanted to ask if you had similar problems. Thanks a lot in advance!

Many greetings
Mirorrn

**Comment by BorisIvanovic** [comment]
Hello @Mirorrn,

Thanks for your question. Hmm, I have to admit I have not encountered this before... 

What happens in the very first training iteration? What is your initial value for the scale? Also, so I understand, the "scale" we're talking about is the log(standard deviation), i.e., https://github.com/StanfordASL/Trajectron-plus-plus/blob/master/trajectron/model/components/gmm2d.py#L42 or something else?

**Comment by Mirorrn** [comment]
Hello @BorisIvanovic,

it was just a small bug and now everything works as usual. Thank you very much for your help!

Many greetings
Mirorrn
