### ISSUE TITLE
how can I see vehicle predicted trajectory in video

### ISSUE THREAD

**Issue by dodeokwangyooo** [StanfordASL/Trajectron-plus-plus#48]
Thank you very much for your code. I would like to ask whether visualization can be carried out, just like the vehicle predicted trajectory can be seen in the video.

**Comment by BorisIvanovic** [comment]
Hi @dodeokwangyooo , thanks for your question. 

The way I've done this before is to save sequential prediction plots as separate images and then create a video from them after the fact. This is actually exactly what test_online.py does, which you'll find in the trajectron/ folder. You can see the figure saving here: https://github.com/StanfordASL/Trajectron-plus-plus/blob/master/trajectron/test_online.py#L233

**Comment by dodeokwangyooo** [comment]
> Hi @dodeokwangyooo , thanks for your question.
> 
> The way I've done this before is to save sequential prediction plots as separate images and then create a video from them after the fact. This is actually exactly what test_online.py does, which you'll find in the trajectron/ folder. You can see the figure saving here: https://github.com/StanfordASL/Trajectron-plus-plus/blob/master/trajectron/test_online.py#L233

Thank you for your reply. I used the "vel_ee", and i saw it's not the first-person perspective. So do you have the first-person perspective vehicle predicted trajectory  in your project ？

**Comment by BorisIvanovic** [comment]
I have not implemented a first-person perspective myself, but you could probably do this easily by adding custom axis limits to the axis object that's used for plotting (I do not know off the top of my head how to rotate figures to be aligned with some heading, but I presume it is possible somehow): https://github.com/StanfordASL/Trajectron-plus-plus/blob/master/trajectron/test_online.py#L204
