### ISSUE TITLE
Unable to get the values in Table 2

### ISSUE THREAD

**Issue by sff1019** [StanfordASL/Trajectron-plus-plus#49]
Hi, I'm trying to run evaluations on ETH dataset using the pre-trained models you've provided. I've followed the instructions in the README, but I cannot seem to get the same of similar values as shown in Table2 in the paper. 
Is there some extra process that I have to follow? 

Thanks!

**Comment by BorisIvanovic** [comment]
I don't know if I'd call it an extra process, but please use this branch if you want the values from the ECCV paper: https://github.com/StanfordASL/Trajectron-plus-plus/tree/eccv2020
