### ISSUE TITLE
Standardization value

### ISSUE THREAD

**Issue by BoLang615** [StanfordASL/Trajectron-plus-plus#50]
Hi,
I appreciate your excellent work. And I have some questions about the project.

1) I have a question about data processing before training. How did you set the standardization 'mean' and 'std' values for each node type? Are these values calculated depending on different datasets? 
If I want to train Trajectron++ on KITTI MOT or Apolloscape, how could I set the 'mean' and 'std' for class CYCLIST?

2) During the training process, https://github.com/StanfordASL/Trajectron-plus plus/blob/37040ca6e3f386c80ab39fbb4aa9984915c94813/trajectron/train.py#L131, the min_ft is set to ph, which will ignore the nodes not having enough future ground truth as ph. If I set the min_ft = 1 and modify the future encoding similar to variable history encoding, do you think it will help for the training process with more samples?

Thank you so much.
Bo

**Comment by BorisIvanovic** [comment]
Hi @BoLang615! Thanks for your questions,

1. There really isn't anything special about those values. I actually used them across different AV datasets, and I didn't run into any problems doing so. When we originally chose them, I think we just approximated the standard deviations of agent tracks in the training scenes. In your case, I personally wouldn't worry about changing values for the same classes. As for CYCLIST, I'd go for something between pedestrian and vehicle, e.g., means that are all zero and position stds = 25, velocity stds = 7, etc...
2. Good question! I think the reason we didn't opt for that is, although it would lead to more data samples (therefore helping the training process with more data), the data samples are "simpler", i.e., shorter time-horizons are easier to predict which might make the model focus on accuracy at short time-horizons and sacrifice long time-horizon performance. I encourage you to try and see what the results will be like, though! 

Hope this helps!
Boris
