### ISSUE TITLE
Data Setup - nuScenes Dataset

### ISSUE THREAD

**Issue by MZ82020** [StanfordASL/Trajectron-plus-plus#54]
Bonjour, 

Concernant la préparation de la base de données Nuscenes, après le téléchargement de la grande base (pas le mini version), Comme elle doit être vue la base sur expériments ( la hiérarchie) s'il vous plait? 
Je n'arrive pas à faire la commande: python process_data.py --data=./v1.0 --version="v1.0-trainval" --output_path=../processed

 Merci

**Comment by BorisIvanovic** [comment]
Bonjour @MZ82020 !

Premièrement, je parle seulement un peu Francais (désolé!), mais je vais essayer! 😛 

Je crois que la hiérarchie est comme ca (du nuScenes-devkit README, [ici](https://github.com/nutonomy/nuscenes-devkit#nuscenes-setup)):

```
/data/sets/nuscenes
    samples	-	Sensor data for keyframes.
    sweeps	-	Sensor data for intermediate frames.
    maps	-	Folder for all map files: rasterized .png images and vectorized .json files.
    v1.0-*	-	JSON tables that include all the meta data and annotations. Each split (trainval, test, mini) is provided in a separate folder.
```

Ainsi, avec les données, la commande que vous voudrez exécuter est: 
```
python process_data.py --data /data/sets/nuscenes --version="v1.0-trainval" --output_path=../processed
```
Notez que vous spécifiez le répertoire de base pour les données dans la commande.

Est-ce que cela aide?
