### ISSUE TITLE
Results Problem

### ISSUE THREAD

**Issue by MZ82020** [StanfordASL/Trajectron-plus-plus#57]
Bonjour, 

La premiere ligne de ce tableau de l'article (ours) représente l modele de base normalement; donc ça réfère au vel_ee. 
Après lorsque j'exécute NusceneQuantitaive, je ne comprends pas pourquoi je n'obtient pas les même résultats du tableau. C'est ours ou ours+M?? 
Pouvez vous m'expliquer s'il vous plait?

![image](https://user-images.githubusercontent.com/94976539/152661909-c1ff39d1-1ac1-49c6-bcbd-18140310703d.png)
![image](https://user-images.githubusercontent.com/94976539/152662004-d04ce41a-a908-4670-996c-da9689733b01.png)
![image](https://user-images.githubusercontent.com/94976539/152661913-451721a7-6c9e-4608-a417-39c0580b9775.png)

**Comment by BorisIvanovic** [comment]
Bonjour @MZ82020 ,

Pour obtenir les même résultats du tableau, vous devez utiliser cette branche: https://github.com/StanfordASL/Trajectron-plus-plus/tree/eccv2020 

Merci,
Boris
