### ISSUE TITLE
Issue on test_online.py

### ISSUE THREAD

**Issue by lsc12318** [StanfordASL/Trajectron-plus-plus#59]
Trajectorn++ is excellent, but sorry, I wanted to ask you a question. In the test_online you provided, I have a question. I found in the debugging that the position, velocity, and acceleration of a single node at the current moment each time the encoder is input. So how is this encoded using the historical trajectory?

**Comment by BorisIvanovic** [comment]
Thank you for the kind words, and sorry for my delayed response!

We compute these online by keeping track of running finite difference values. For example, at timestep `t` we can find the velocity from the previous timestep's values by doing:
```
vel[t] = (position[t] - position[t-1])/dt
```
This is what our preprocessing script does when it preprocesses the dataset (you can see this in the preprocess_data.py scripts found in the experiments/<dataset> folders)
