### ISSUE TITLE
Process nuscenes test dataset

### ISSUE THREAD

**Issue by TsuTikgiau** [StanfordASL/Trajectron-plus-plus#6]
Hello!
I'd like to generate the pkl file of the test set using your code. I have done the train/val part successfully, but for the test set the following code asks for a individual test annotation:

https://github.com/StanfordASL/Trajectron-plus-plus/blob/3588a3ebea472623dce537a528801ac6b441fac2/data/nuScenes/process_nuScenes.py#L137

I didn't find such a file from the website of nuScenes dataset. Do I miss something or does this file come from other location? Thank you in advance!

**Comment by BorisIvanovic** [comment]
Hi @TsuTikgiau , thanks for your question.

We got that from the nuScenes dataset website at https://www.nuscenes.org/tracking?externalData=all&mapData=all&modalities=Any (scroll down to the "Baselines" heading).

**Comment by BorisIvanovic** [comment]
I'll close this now, but please feel free to re-open it if you have further questions!
