### ISSUE TITLE
Bugs during data preprocessing for nuScenes 

### ISSUE THREAD

**Issue by MeiliMa** [StanfordASL/Trajectron-plus-plus#65]
The bug is at https://github.com/StanfordASL/Trajectron-plus-plus/blob/58248eea68c8b0836dce04a5be09a6ca198a6acc/experiments/nuScenes/process_data.py#L339-L343

I assume that these lines forcefully let a vehicle to become static (parked) if its displacement is less than 1m. This may be reasonable. But, it is a bug to repeat the data `max_timesteps + 1` times, since the vehicle may not appear at the first frame. This bug will introduce many extra frames where there is only a parked vehicle, which is easy for prediction.

**Comment by BorisIvanovic** [comment]
Good catch! In reality we should have only repeated the position/heading the number of frames that the vehicle was present in the scene.

Thankfully, I am about to release a new, and much cleaner, multi-dataset data-loading framework that does not perform small hacks like this (and which therefore does not have this bug).

Until then (and until I switch over this codebase to using the new dataloader), I will leave this issue open for others' benefit.
