### ISSUE TITLE
Evaluation metrics

### ISSUE THREAD

**Issue by noparkee** [StanfordASL/Trajectron-plus-plus#68]
Hello,
Thank you for your work! I  have some questions about the evaluation code.

In experiments/pedestrians.evaluate.py, there are 4 types of metrics. (most likely, mode z, best of 20 and full)
I am a newbie in this field, so don't know the details about these metric.

1. Can you tell me the difference between them? 
2. And table 2 in your paper, Is (a) obtained by "most likely" and (b) obtained by "best of 20"?

Thank you!

**Comment by noparkee** [comment]
I solved it. I was mistaken.

**Comment by ot4f** [comment]
@noparkee I don't know too, can you tell me some details.
