### ISSUE TITLE
Encoding future robot trajectories

### ISSUE THREAD

**Issue by keanepotato** [StanfordASL/Trajectron-plus-plus#69]
Hi Boris,

I have a question regarding Trajectron's encoding of future robot trajectories. Particularly, I am looking to do the following:

1. From the ETH dataset, change the one random human node from to a robot, by changing the nodeType to 'ROBOT'
2. Encode the node's future trajectory as the 'robot' trajectory.

However, I am running into a few issues when running the test_online.py file -  I obtain an assertion error
`File "/home/kong35/human_prediction_keane_dev/Trajectron-plus-plus/trajectron/model/online/online_trajectron.py", line 201, in incremental_forward
    assert robot_present_and_future.shape[1] == prediction_horizon + 1
AssertionError`

I believe the issue is related to this segment of the code where I am obtaining the 'robot_present_and_future'.
https://github.com/StanfordASL/Trajectron-plus-plus/blob/58b9763d02b9c90e1b67dad1026bf0b1b9e322a9/trajectron/test_online.py#L179-L197
I am specifying the state of the robot in config.json as `"state": "ROBOT2": {"position": ["y", "x"], "velocity": ["y", "x"], "acceleration": ["y", "x"]}` Am I implementing the wrong inputs for this? I realise that the test_online.py file is originally supposed to be run on the nuScenes models where the robot node is a vehicle node type, and the state is  `"state": "VEHICLE": {"position": ["x", "y"], "velocity": ["x", "y"], "acceleration": ["x", "y"], "heading": ["\u00b0", "d\u00b0"]`

**Comment by BorisIvanovic** [comment]
Hi Keane,

That particular issue that you're seeing is one of our [internal checks](https://github.com/StanfordASL/Trajectron-plus-plus/blob/58b9763d02b9c90e1b67dad1026bf0b1b9e322a9/trajectron/model/online/online_trajectron.py#L257) which ensures that the robot present and future passed in actually contains that much data. In particular, it's checking that dimension 1 of  `robot_present_and_future` has prediction horizon + 1 number of timesteps (1 for the current timestep, and prediction horizon for the future timesteps).

I don't think that you're implementing the wrong inputs for this, and indeed I think you're correctly setting it in the config (you could also debug the online test script to make sure you're getting the states you want, in case you're ever unsure). Rather, I think that you're not getting the correct amount of timesteps or there is a mismatch between what you're passing to the function and how much prediction horizon you're telling the model to predict.

I hope this helps!
Boris

PS. Just giving you a heads up that I may respond a bit slowly to your email, things are quite busy these days unfortunately... Sorry!

**Comment by keanepotato** [comment]
Hi Boris,

Thank you for your help on this. And no worries about responding promptly to the email :) I understand that you are busy!  

Regarding the encoding future robot trajectories, I managed to fix the assertion error, but I ran into another one while using the same approach (points 1 and 2 of my first comment in this thread above): 

`Traceback (most recent call last):
  File "test_and_visualise_trajectron.py", line 1051, in <module>
    node_prediction_dict_at_timestep, all_node_ADEs, result_ade,nodes_ground_truth,nodes_predictions,robot_ground_truth = get_multiple_predictions(img_tag,model_name,full_env,test_dict[robot_node_id],6,50, start_end_timesteps,CVaR_parameters,examine_pass= False, calculate_ADE=False)
  File "test_and_visualise_trajectron.py", line 592, in get_multiple_predictions
    full_dist=True)
  File "/home/kong35/human_prediction_keane_dev/Trajectron-plus-plus/trajectron/model/online/online_trajectron.py", line 212, in incremental_forward
    maps)
  File "/home/kong35/human_prediction_keane_dev/Trajectron-plus-plus/trajectron/model/online/online_mgcvae.py", line 390, in encoder_forward
    self.latent.p_dist = self.p_z_x(mode, self.x)
  File "/home/kong35/human_prediction_keane_dev/Trajectron-plus-plus/trajectron/model/mgcvae.py", line 752, in p_z_x
    h = F.dropout(F.relu(dense(x)),
  File "/home/kong35/anaconda3/envs/trajectron++/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kong35/anaconda3/envs/trajectron++/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 87, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/kong35/anaconda3/envs/trajectron++/lib/python3.6/site-packages/torch/nn/functional.py", line 1370, in linear
    ret = torch.addmm(bias, input, weight.t())
RuntimeError: size mismatch, m1: [2 x 192], m2: [64 x 32] at /pytorch/aten/src/TH/generic/THTensorMath.cpp:136`

I tried a number of solutions - reshaping the tensors etc. which I don't think really works :( , but I think the error might be related to map encoding? I think this might be the case because I am omitting map encoding when I run the above code(on ETH), and I get the same error when I run the test_online.py on the nuScenes dataset (entering the argument --incl_robot_node but omit --map_encoding). 

As I am interested in encoding future robot trajectories on the ETH dataset (where map encoding isn't supposed), is there a way to do this without including the map_encoding? Or conversely, is the error unrelated to that? 

Thank you very much Boris!

**Comment by Leon0402** [comment]
Regarding the first issue: I think this is a bug in the current implementation. See 

https://github.com/StanfordASL/Trajectron-plus-plus/blob/58b9763d02b9c90e1b67dad1026bf0b1b9e322a9/trajectron/test_online.py#L188-L193

here the prediction horizon is hardcoded to 6. Instead it should be `hyperparams['prediction_horizon']` to match your config. 

Regarding your second issue: Your input size is calculated here

https://github.com/StanfordASL/Trajectron-plus-plus/blob/58b9763d02b9c90e1b67dad1026bf0b1b9e322a9/trajectron/model/mgcvae.py#L159-L168

But as far as I know this only has a effect if training a new model. Because with a pretrained model the architecture is already in the model. So you can probably try to modify your pytorch model layers so they take the input size you want. But I'm not sure how good the results will be. You will need some training at least then otherwise your output is garbage I assume. 
But no expert here ;) 

(The easiest fix is obviously to train a new model from scratch with exactly the configuration you want)
