### ISSUE TITLE
How to Convert Model to Tensorrt

### ISSUE THREAD

**Issue by tlgkyn06** [StanfordASL/Trajectron-plus-plus#71]
Hi, I would like to increase performance by converting model to tensorrt.

Besides yolo,resnet etc. this model uses decode-encode forward structure. For regular pytorch models(yolo,resnet,alexnet) this repo can be used (https://github.com/NVIDIA-AI-IOT/torch2trt) but I could not adapt it to trajectron. 

How can I convert Trajectron model to Tensorrt?

**Comment by BorisIvanovic** [comment]
Thanks for your question! Unfortunately, I do not have any experience with converting models to tensorrt, so I'm not able to give any advice at this time...
