### ISSUE TITLE
Question about the input and output (states of agents)

### ISSUE THREAD

**Issue by thisishale** [StanfordASL/Trajectron-plus-plus#72]
Hello,

Thank you for sharing the code.
Are the output states of agents the subtraction between the future position and current position? or just the future position itself?

**Comment by BorisIvanovic** [comment]
Hi @thisishale, it is indeed the difference in positions. You can see this in, e.g., the single integrator dynamics code using a cumulative sum: https://github.com/StanfordASL/Trajectron-plus-plus/blob/master/trajectron/model/dynamics/single_integrator.py#L22
