### ISSUE TITLE
 Then, download the map expansion pack (v1.1) and copy the contents of the extracted maps folder into the experiments/nuScenes/v1.0-mini/maps folder.

### ISSUE THREAD

**Issue by qq1628qq** [StanfordASL/Trajectron-plus-plus#74]
Hi,where is the v1.1,i not found in nuscene web.thanks

**Comment by BorisIvanovic** [comment]
The README is a little bit old in this respect (sorry about that!). You should be able to use the latest map expansion pack (which I believe is v1.3 now)
