### ISSUE TITLE
"Robot future is none"

### ISSUE THREAD

**Issue by zhyzhyzhy123** [StanfordASL/Trajectron-plus-plus#77]
I follow the code in [NuScenes Qualitative.ipynb](https://github.com/StanfordASL/Trajectron-plus-plus/blob/master/experiments/nuScenes/NuScenes%20Qualitative.ipynb), but when I test the last part  'Prediction using velocity output and map', I cannot find the config file ee_vel, so I use the config of robot. But I got an error in mgcvae.py. The error is "Robot future is none". So is the config of ee_vel same with the config of robot? And how can I fix the error?

**Comment by BorisIvanovic** [comment]
Have you looked in this folder? https://github.com/StanfordASL/Trajectron-plus-plus/tree/master/experiments/nuScenes/models/vel_ee 

All of the model configs you can find here for nuScenes: https://github.com/StanfordASL/Trajectron-plus-plus/tree/master/experiments/nuScenes/models
