### ISSUE TITLE
How to replicate the results in your paper

### ISSUE THREAD

**Issue by xiaxx244** [StanfordASL/Trajectron-plus-plus#78]
Hi, first of all. This is an interesting paper and I really like the idea of trajectron++. I am currently working on a project related to that and I need to replicate the results in your paper. However, the visualization results and the quantitative  evaluation results I obtained is quite different from your paper. I am wondering what is your training parameters and epochs and how you train your model? Can you release your trained model and the train and test split publicly ? Thanks!

**Comment by BorisIvanovic** [comment]
Hi @xiaxx244 , If you _absolutely, at all costs_ need to replicate the model from the 2020 paper, then take a look at the `eccv2020` branch: https://github.com/StanfordASL/Trajectron-plus-plus/tree/eccv2020 

Having said that, you can (and should) feel free to use the much more updated repository here: https://github.com/NVlabs/adaptive-prediction (just make sure not to use any of the adaptive features if you only want to compare to T++).
