### ISSUE TITLE
Dists can't match the preds in test_online.py in visualization

### ISSUE THREAD

**Issue by salt0107fish** [StanfordASL/Trajectron-plus-plus#79]
Hi,
Thanks for your work. I have a problem in test_online.py
`fig, ax = plt.subplots()`
`vis.visualize_distribution(ax,
                                   dists)`
`vis.visualize_prediction(ax,
                                 {timestep: preds},
                                 eval_scene.dt,
                                 hyperparams['maximum_history_length'],
                                 hyperparams['prediction_horizon'])`
The dists do not match the preds in the output figs. It's too small. Is there something wrong in the code?

**Comment by BorisIvanovic** [comment]
Hi, I don't know how to reproduce the error or what error you're seeing. I will close this for now, but please let me know if this is still an issue for you and what you're seeing on your end. Thanks!
