### ISSUE TITLE
NuScenes database version not found error  (v1.0-mini)

### ISSUE THREAD

**Issue by mvignaga** [StanfordASL/Trajectron-plus-plus#80]
Dear author,

I'm following your guide for testing the model but got stuck when calling: 
`python process_data.py --data=.\v1.0-mini --version="v1.0-mini" --output_path=../processed`
with the following error:
```
File "process_data.py", line 472, in <module>
process_data(args.data, args.version, args.output_path, args.val_split)
File "process_data.py", line 402, in process_data
nusc = NuScenes(version=version, dataroot=data_path, verbose=True)
File "C:\Users\user\anaconda3\envs\trajectron++\lib\site-packages\nuscenes\nuscenes.py", line 54, in __init__
assert osp.exists(self.table_root), 'Database version not found: {}'.format(self.table_root)
AssertionError: Database version not found: .\v1.0-mini\v1.0-mini
```
Inside experiments/nuScenes I placed the dataset (v1.0-mini.tgz) and map expansion (v1.3) into 
```
+---v1.0-mini 
|   \---maps 
| -------boston-seaport.json
| -------singapore-hollandvillage.json
| -------singapore-onenorth.json
| -------singapore-queenstown.json  
```

I tried to fix it by removing the extra v1.0-mini from the path like:
`python process_data.py --data=.\ --version="v1.0-mini" --output_path=../processed`

producing:
```
File "process_data.py", line 472, in <module>
process_data(args.data, args.version, args.output_path, args.val_split)
File "process_data.py", line 402, in process_data
nusc = NuScenes(version=version, dataroot=data_path, verbose=True)
File "C:\Users\user\anaconda3\envs\trajectron++\lib\site-packages\nuscenes\nuscenes.py", line 101, in __load_table__
with open(osp.join(self.table_root, '{}.json'.format(table_name))) as f:
FileNotFoundError: [Errno 2] No such file or directory: '.\\v1.0-mini\\category.json'
```

Double checked the procedure but can't figure out my mistake, could you help me?

**Comment by BorisIvanovic** [comment]
Sorry for the late reply! Does this help? https://github.com/StanfordASL/Trajectron-plus-plus/issues/54

I believe your file hierarchy might be incorrect; the maps should be outside of the v1.0-mini folder.

**Comment by mvignaga** [comment]
Yes it helped! I made some mistake extracting dataset or map files, thank you.
