### ISSUE TITLE
z_mode setting during evaluation

### ISSUE THREAD

**Issue by centiLinda** [StanfordASL/Trajectron-plus-plus#84]
Hi Boris,

In the training script, when predicting the most-likely results, z_mode is set to True for both visualisation and evaluation:
https://github.com/StanfordASL/Trajectron-plus-plus/blob/1031c7bd1a444273af378c1ec1dcca907ba59830/trajectron/train.py#L295
https://github.com/StanfordASL/Trajectron-plus-plus/blob/1031c7bd1a444273af378c1ec1dcca907ba59830/trajectron/train.py#L418

In the evaluation script, however, z_mode is set to False:
https://github.com/StanfordASL/Trajectron-plus-plus/blob/1031c7bd1a444273af378c1ec1dcca907ba59830/experiments/pedestrians/evaluate.py#L82

Is there a reason for this choice? Both generate most-likely results, but one is from the most-likely latent state, one samples from all latent states. They lead to slightly different results and I wonder which setting you used for the reported results.

**Comment by BorisIvanovic** [comment]
Hello, as can be seen in the same file, the choice of `z_mode` depends on the particular evaluation being conducted (indicated by the comments above the evaluation, e.g., https://github.com/StanfordASL/Trajectron-plus-plus/blob/1031c7bd1a444273af378c1ec1dcca907ba59830/experiments/pedestrians/evaluate.py#L68)
