### ISSUE TITLE
Number of components of the GMM in the decoder

### ISSUE THREAD

**Issue by ArielleZhang** [StanfordASL/Trajectron-plus-plus#86]
In all the config files for the pretrained model N is set to 1, after reading the code, I think N here stands for the number of components of the GMM. Is there a reason why N is always set to 1? If we want a GMM with more than one component should we change N? Because I did see in ```gmm2d.py``` with more than one component is implemented in the code. Appreciate your help!

**Comment by BorisIvanovic** [comment]
Hi @ArielleZhang, my apologies for the confusion, N is indeed set to 1 (denoting that there is 1 Gaussian component per mode), but K is set to 25 (denoting that there are 25 modes). So overall it's a mixture model of 25 unimodal gaussians => GMM with 25 components. You can see this in `discrete_latent.py`.

I hope this helps!

**Comment by ArielleZhang** [comment]
> Hi @ArielleZhang, my apologies for the confusion, N is indeed set to 1 (denoting that there is 1 Gaussian component per mode), but K is set to 25 (denoting that there are 25 modes). So overall it's a mixture model of 25 unimodal gaussians => GMM with 25 components. You can see this in `discrete_latent.py`.
> 
> I hope this helps!

That makes a lof of sense! Thanks for the reponse!

**Comment by ArielleZhang** [comment]
Just to clarify for anyone who's wondering, in ```gmm2d.py``` there is a GMM with 2 components implemented by checking the shape of the means (mus), and when training on the pedestrian datasets, we are running a 2D GMM, but this 2 did not come from N, instead it's ```N * self.pred_state_length = 2```. So far I think for vehicles is only running with 1D GMM, but correct me if I'm wrong.
