### ISSUE TITLE
nuScenes process_data.py doesn't work

### ISSUE THREAD

**Issue by elsoroka** [StanfordASL/Trajectron-plus-plus#95]
Hi,
I have been trying to use this model but unfortunately the process_data.py script seems to be broken.
Steps to reproduce:
1. check out Trajectron-plus-plus repo
2. install requirements.txt
3. download nuScenes v1.0-mini dataset and v1.1 map expansion
4. unzip the nuScenes data in a folder `Trajectron-plus-plus/experiments/nuScenes/data`
5. run the command `python3.7 process_data.py --data=./data --version="v1.0-mini" --output_path=../processed`

`python3.7 -m pip install -r requirements.txt ` reports all requirements satisfied

Output of `ls -l` on `Trajectron-plus-plus/experiments/nuScenes/data`:
> drwxrwxr-x  2 esoroka esoroka 4096 Jan 16  2020 maps
> drwxrwxr-x 14 esoroka esoroka 4096 Mar 17  2019 samples
> drwxrwxr-x 14 esoroka esoroka 4096 Mar 17  2019 sweeps
> drwxr-xr-x  2 esoroka esoroka 4096 Mar 22  2019 v1.0-mini

Result (the invalid value line repeats hundreds of times):
/home/esoroka/anaconda3/lib/python3.7/site-packages

> /shapely/set_operations.py:133: RuntimeWarning: invalid value encountered in intersection
>   return lib.intersection(a, b, **kwargs)
>   0%|                                                                                                                                                                       | 0/8 [00:23<?, ?it/s]
> Traceback (most recent call last):
>   File "process_data.py", line 472, in <module>
>     process_data(args.data, args.version, args.output_path, args.val_split)
>   File "process_data.py", line 432, in process_data
>     scene = process_scene(ns_scene, env, nusc, data_path)
>   File "process_data.py", line 267, in process_scene
>     map_mask = (nusc_map.get_map_mask(patch_box, patch_angle, layer_names, canvas_size) * 255.0).astype(
>   File "/home/esoroka/anaconda3/lib/python3.7/site-packages/nuscenes/map_expansion/map_api.py", line 345, in get_map_mask
>     return self.explorer.get_map_mask(patch_box, patch_angle, layer_names, canvas_size)
>   File "/home/esoroka/anaconda3/lib/python3.7/site-packages/nuscenes/map_expansion/map_api.py", line 610, in get_map_mask
>     map_mask = self.map_geom_to_mask(map_geom, local_box, canvas_size)
>   File "/home/esoroka/anaconda3/lib/python3.7/site-packages/nuscenes/map_expansion/map_api.py", line 559, in map_geom_to_mask
>     layer_mask = self._layer_geom_to_mask(layer_name, layer_geom, local_box, canvas_size)
>   File "/home/esoroka/anaconda3/lib/python3.7/site-packages/nuscenes/map_expansion/map_api.py", line 1481, in _layer_geom_to_mask
>     return self._polygon_geom_to_mask(layer_geom, local_box, layer_name, canvas_size)
>   File "/home/esoroka/anaconda3/lib/python3.7/site-packages/nuscenes/map_expansion/map_api.py", line 1568, in _polygon_geom_to_mask
>     map_mask = self.mask_for_polygons(new_polygon, map_mask)
>   File "/home/esoroka/anaconda3/lib/python3.7/site-packages/nuscenes/map_expansion/map_api.py", line 1501, in mask_for_polygons
>     exteriors = [int_coords(poly.exterior.coords) for poly in polygons]
> TypeError: 'MultiPolygon' object is not iterable

A [version of the process_data script](https://github.com/zqzqz/AdvTrajectoryPrediction/blob/master/data/nuScenes/preprocessing.py) I found in another repo works, but it finds "0 scenes" so no .pkl file can be generated, thus the NuScenes Qualitative notebook doesn't work.

**Comment by elsoroka** [comment]
Hi,
Good news! I have solved this issue. The problem is related to versioning of Shapely and nuscenes-devkit. I can report Shapelu 1.8.5 and nuscenes-devkit 1.1.10 don't have this error.

**Comment by BorisIvanovic** [comment]
Fantastic! Glad to hear that.
